version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop_services.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_apache_codedeploy.sh
      timeout: 300
      runas: root
